services:
  - type: web
    name: line-orderbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        value: your-channel-access-token-here
      - key: CHANNEL_SECRET
        value: your-channel-secret-here
      - key: GOOGLE_SHEET_KEY
        value: your-google-sheet-id-here
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/credentials.json  # 供 gspread/google-auth 使用

# Secret file mount for credentials.json
files:
  - source: credentials.json
    destination: /etc/secrets/credentials.json

